### ISSUE TITLE
Support Tizen

### ISSUE THREAD

**Issue by hs0225** [Samsung/js-remote-test#109]
To support Tizen, we need to work a few things below.

- [x] remote test 
- [x] calculate binary size
- [x] calculate memory size for testcase
- [x] publish to `https://samsung.github.io/iotjs-test-results`

**Comment by rtakacs** [comment]
Good idea. I will start to implement that target into the test system.

**Comment by hs0225** [comment]
@rtakacs I am now implementing a system to test iot.js. Please hold on your work for a while.

**Comment by rtakacs** [comment]
@hs0225 Okay :)

**Comment by rtakacs** [comment]
@hs0225 I start to work on the binary size calculation.

**Comment by rtakacs** [comment]
The #129 pull request enables the memory measurement for Tizen devices.

**Comment by rtakacs** [comment]
I'm closing this issue since all the defined points are completed.
