### ISSUE TITLE
Freya dependency

### ISSUE THREAD

**Issue by tosyu** [Samsung/js-remote-test#11]
Sometimes boards are disconnected from the internet, could we make freya dependancy (for RPI) optional? 

Or maybe crosscompile it on linux and send it with the os (like iotjs or jerry-script)?

**Comment by rtakacs** [comment]
Yes, the cross compilation is a planned (low priority) feature, but we don't have any time to do it. Would you like to do this modification?

**Comment by rtakacs** [comment]
https://github.com/szeged/Freya#cross-compile-for-arm

**Comment by rtakacs** [comment]
This issue was fixed by #38.
