### ISSUE TITLE
Please share firebase database configuration

### ISSUE THREAD

**Issue by tosyu** [Samsung/js-remote-test#12]
I have the data on a firebase database (so write access works). The service responds with available keys, you can check on https://tosyu.github.io/remote-testrunner/ for RPI2. It renders 1 node one the chart (just one result was posted). But there is a problem with rendering the test results (below the chart). I'm guessing there is something wrong with my database configuration:

```json
{
  "rules": {
    ".read": true,
    ".write": "auth != null",
    "$uid": {
      ".write": "$uid === auth.uid"
    }
  }
}
```

Please help :cry:

**Comment by robertsipka** [comment]
@tosyu : This is a bug in the rendering method. If the database contains only one element then the results are not rendered. I've just uploaded a PR #13 for that.
About the configuration: You should indexing the date. You can define that via the `.indexOn` property.

**Comment by tosyu** [comment]
Ok, thx for the info, the issue can be closed
