### ISSUE TITLE
Binary size in daily report is same for all targets

### ISSUE THREAD

**Issue by glistening** [Samsung/js-remote-test#43]
Binary size in https://samsung.github.io/js-remote-test/# are reported as same for STM32, RPI2, and Artik053 respectively. Comment in https://github.com/Samsung/js-remote-test/blob/master/API/application/iotjs.py#L112 says it is intentional. But we would like to know binary size for each platform.

**Comment by rtakacs** [comment]
@glistening: `nuttx.bin` contains the tests (by ROMFS) as well. Should we have a NuttX build without the tests and report that size?

**Comment by glistening** [comment]
@rtakacs Yes. We would like to know the minimal size. (i.e. without debug symbol, unit tests, ...)

**Comment by hs0225** [comment]
One way to measure it is to use `arm-none-eabi-size` to get the size from static library file(*.a).

**Comment by rtakacs** [comment]
In the **build/arm-nuttx/release/lib** folder there are more static libraries:

`libhttpparser.a  libiotjs.a  libjerry-core.a  libjerry-ext.a  libjerry-libm.a  libtuv.a`

Is it enough just aggregate the main segments (**.text**, **.data**, **.rodata**) to approximate the binary size? In this case the binary size of the RPi2 target also should be use this mechanism (and not the `ls` command that currently is used).  

The binary size chart on the page can be an [aggregated chart](https://support.content.office.net/en-us/media/e0389181-da18-4762-9988-ab24a7af3fc5.jpg) that can show the **.text** **.data** **.rodata** values.

**Comment by glistening** [comment]
@rtakacs It seems ok. But I would like to get confirmed from @hs0225.

**Comment by LaszloLango** [comment]
The archive files contain unused symbols too. Link time optimization drop those symbols from the final binary, so reporting the archive sizes could be misleading. What about analyzing the map file of the linker? It might give us a more precise result.

**Comment by rtakacs** [comment]
@LaszloLango Yes, you are right. Maybe the **map** file should be processed, because that contains  the final **.text**, **.data**, **.rodata** sizes.

**Comment by glistening** [comment]
@LaszloLango, @rtakacs In general, you're right. But @hs0225 suggested this approach for some reason. He showed numbers that it shows not much differences. He will contact and explain you on IRC for details. I am ok for map approach if @hs0225 agrees.

**Comment by hs0225** [comment]
@LaszloLango @rtakacs I agree to use the map file because it's the right way. FYI, TizenRT provides a utility to analyze map files.(os/tools/memstats_gnueabil.py)

**Comment by rtakacs** [comment]
@hs0225 Yes, #53 uses the linker map file (on both targets) to approximate the binary size. Since #53 is landed, I'm closing this issue.
