### ISSUE TITLE
artik053 does not build

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/js-remote-test#52]
I'd like to build the `artik053` device, but it fails.

**command**
`python driver.py --device=artik053 --app=iotjs --buildtype=debug`

**output**
```
echo "create .version file"; \
tools/version.sh -v 1.0 .version; \
chmod 755 .version
create .version file
LN: include/arch to arch/arm/include
LN: arch/arm/src/board to arch/arm/src/artik053/src
LN: include/apps to ../apps/include
make: *** No rule to make target '/mnt/work/Samsung/js-remote-test/projects/iotjs/build/arm-tizenrt/debug/lib/libhttpparser.a', needed by '../build/output/libraries/libhttpparser.a'.  Stop.
make: *** Waiting for unfinished jobs....
LN: arch/arm/src/chip to arch/arm/src/s5j
```

**Comment by LaszloLango** [comment]
CC: @hs0225

**Comment by LaszloLango** [comment]
There is a comment in `iotjs.py:154`: `# For artik053, build IoT.js in os.build.`
But it looks like tizenrt.py does not build it and this is why `libhttpparser.a` does not exist. I tried to build it by myself but I get another error.

**command:**
`tools/build.py --target-arch=arm --target-os=tizenrt`

**output**
`--sysroot needed for nuttx target`

**Comment by hs0225** [comment]
@LaszloLango You can build IoT.js for TizenRT with following command.
`tools/build.py --target-arch=arm --target-os=tizenrt --target-board=artik05x --sysroot=../TizenRT/os`.

I have no problem using js-remote-test for artik053. Would you try building with the [guide](https://github.com/Samsung/iotjs/blob/master/docs/build/Build-for-ARTIK053-TizenRT.md)?

**Comment by LaszloLango** [comment]
@hs0225 thanks for your answer. It turned out it works with sudo, but I don't understand why sudo is needed for the build.

`sudo python driver.py --device=artik053 --app=iotjs`

**Comment by glistening** [comment]
I also failed to build js-remote-test with latest version.

```
$ python driver.py --device=artik053 --app=iotjs --buildtype=debug
Traceback (most recent call last):
  File "driver.py", line 17, in <module>
    import API
  File "/home/brian/iotjs/js-remote-test/API/__init__.py", line 16, in <module>
    import device
  File "/home/brian/iotjs/js-remote-test/API/device/__init__.py", line 15, in <module>
    import artik053
  File "/home/brian/iotjs/js-remote-test/API/device/artik053.py", line 16, in <module>
    import connection
  File "/home/brian/iotjs/js-remote-test/API/device/connection/__init__.py", line 15, in <module>
    import serialcom
  File "/home/brian/iotjs/js-remote-test/API/device/connection/serialcom.py", line 15, in <module>
    import serial
ImportError: No module named serial
```

**Comment by glistening** [comment]
I think this is different bug. I will create another issue.

**Comment by glistening** [comment]
@LaszloLango Could we close this issue? Or do we need more investigation?

**Comment by LaszloLango** [comment]
Let's close it, although it would be nice if we could find out the reason why `sudo` is needed for build in some systems.
