### ISSUE TITLE
Do not duplicate the labels at charts

### ISSUE THREAD

**Issue by rtakacs** [Samsung/js-remote-test#78]
Currently the labels on the charts are duplicated. This means that there are labels at the bottom of the charts (e.g. target-profile binary size, minimal-profile binary size) that are also located on the tooltips (when pointing to a point in the chart).

In case of tooltips, it should be enough just use a color (orange rectangle, blue rectangle) to identify the information, because the charts (at the bottom) already define that.

To make a correct decision (remove labels or not), I've published the idea on my github repository that you can check:

https://samsung.github.io/js-remote-test/   (official)
https://rtakacs.github.io/js-remote-test/      (local developement, removed the labels from tooltips)

**Comment by rtakacs** [comment]
@glistening @rsipka : What do you think about this change?

**Comment by robertsipka** [comment]
@rtakacs : It's ok for me.

**Comment by bzsolt** [comment]
I am in favour of this change.

**Comment by rsipka** [comment]
@rtakacs you meant @robertsipka ? :)

**Comment by glistening** [comment]
@rtakacs I like this change.

**Comment by rtakacs** [comment]
Closing since #82 is landed.
