### ISSUE TITLE
Use stable TizenRT hash like in case of NuttX

### ISSUE THREAD

**Issue by rtakacs** [Samsung/js-remote-test#80]
Currently, TizenRT is always updated to the latest master before testing. Since TizenRT is continuously changing, we should use a stable (TizenRT) hash in js-remote-test. (In case of NuttX, we use nuttx-7.19 hash tag.)

**Comment by rtakacs** [comment]
For example, **js-remote-test** doesn't work with the latest TizenRT master on artik053:

```
error: build/configs/artik053/artik053_download.sh: No such file or directory
error: build/configs/artik053/tools/openocd/artik053.cfg: No such file or directory

[Failed - git] Not null exit value
```

**Comment by glistening** [comment]
@rtakacs I agree. We cannot use the latest version TizenRT. But we may need to run another run test with latest TizenRT for identifying the problem of latest TizenRT, and fixing or reporting.

**Comment by hs0225** [comment]
@rtakacs I agree your opinion. We will have difficulty managing updated TizenRT every time. I want to fix `1.1_Public_Release` tag for it.

**Comment by bzsolt** [comment]
That TizenRT tag was used by the latest IoT.js measurement on Artik053.

**Comment by rtakacs** [comment]
Closing this issue since #87 is landed.
